const fs = require('fs');
const path = require('path');

function parseArgs(argv) {
  const args = {
    summary: '',
    redundancy: '',
    output: '',
  };
  for (let index = 0; index < argv.length; index++) {
    const arg = argv[index];
    if (arg === '--summary') args.summary = argv[++index] || '';
    else if (arg === '--redundancy') args.redundancy = argv[++index] || '';
    else if (arg === '--output') args.output = argv[++index] || '';
    else if (arg === '--help' || arg === '-h') {
      console.log([
        'Usage:',
        '  node scripts/generate_corpus_tex.js',
        '    --summary <large_corpus_summary.json>',
        '    --redundancy <redundancy_sensitivity.json>',
        '    --output <corpus_numbers.tex>',
      ].join('\n'));
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  for (const field of ['summary', 'redundancy', 'output']) {
    if (!args[field]) throw new Error(`--${field} is required`);
  }
  return args;
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8').replace(/^\uFEFF/, ''));
}

function integer(value) {
  return Math.round(Number(value)).toLocaleString('en-US');
}

function decimal(value, digits) {
  return Number(value).toFixed(digits);
}

function percent(rate, digits = 2) {
  return `${decimal(Number(rate) * 100, digits)}\\%`;
}

function command(name, value) {
  return `\\providecommand{\\${name}}{${value}}`;
}

function byName(entries, name) {
  const item = (entries || []).find(entry => entry.name === name);
  if (!item) throw new Error(`Missing summary entry: ${name}`);
  return item;
}

function countByName(entries, name) {
  return Number((entries || []).find(entry => entry.name === name)?.count || 0);
}

function maxCloneShift(redundancy) {
  const sensitivity = redundancy.detectionSensitivity;
  const base = sensitivity.project;
  const alternatives = [
    sensitivity.onePerExactCloneCluster,
    sensitivity.onePerNearCloneCluster,
  ];
  let maximum = 0;
  for (const alternative of alternatives) {
    for (const key of ['apiRate', 'sinkRate', 'taintRate']) {
      maximum = Math.max(
        maximum,
        Math.abs(Number(alternative[key]) - Number(base[key])) * 100,
      );
    }
  }
  return maximum;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const summary = readJson(args.summary);
  const redundancy = readJson(args.redundancy);
  const validation = summary.scope?.singleRunValidation;
  if (!validation || validation.status !== 'complete' || validation.resume) {
    throw new Error('Corpus macros require a validated, non-resumed single run');
  }
  if (summary.scope.reports !== validation.projectCount) {
    throw new Error('Summary report count does not match the run manifest');
  }
  if (summary.scope.batchErrors.length !== 0) {
    throw new Error('Summary contains batch errors');
  }
  if (redundancy.detectionSensitivity?.project?.projects !== summary.scope.reports) {
    throw new Error('Redundancy sensitivity does not match the corpus summary');
  }
  const strictChecks = summary.traceability?.strictReportChecks;
  if (strictChecks?.checked !== summary.scope.reports
      || (strictChecks?.failures || []).length !== 0) {
    throw new Error('Per-report strictness checks are incomplete or failed');
  }

  const totals = summary.totals;
  const rates = summary.projectRates;
  const distributions = summary.distributions;
  const concentration = summary.concentration.apiUsages;
  const trace = summary.traceability;
  const correlations = summary.scalability.correlations;
  const categories = summary.evidence.profilingCategories;
  const sinks = summary.evidence.sinkTypes;
  const provenance = summary.evidence.flowProvenance;
  const lines = [
    '% Generated by scripts/generate_corpus_tex.js. Do not edit by hand.',
    `% Summary: ${path.basename(args.summary)}`,
    `% Manifest SHA-256: ${validation.manifestSha256}`,
    command('CorpusCandidateProjects', integer(redundancy.corpusStructure.projects)),
    command('CorpusProjects', integer(summary.scope.reports)),
    command('CorpusFiles', integer(totals.files)),
    command('CorpusMethods', integer(totals.methods)),
    command('CorpusApiOccurrences', integer(totals.privacyApiUsages)),
    command('CorpusApiProjects', integer(rates.apiPositive.count)),
    command('CorpusApiRate', percent(rates.apiPositive.rate)),
    command('CorpusSinkObservations', integer(totals.sinks)),
    command('CorpusSinkProjects', integer(rates.sinkPositive.count)),
    command('CorpusSinkRate', percent(rates.sinkPositive.rate)),
    command('CorpusPaths', integer(totals.taintFlows)),
    command('CorpusPathProjects', integer(rates.taintPositive.count)),
    command('CorpusPathRate', percent(rates.taintPositive.rate)),
    command('CorpusRawPaths', integer(totals.rawTaintFlows)),
    command('CorpusIfdsRawPaths', integer(totals.ifdsRawFlows)),
    command('CorpusAsyncRawPaths', integer(totals.callbackRawFlows)),
    command('CorpusDuplicatePathsRemoved', integer(totals.duplicateTaintFlowsRemoved)),
    command('CorpusIfdsPaths', integer(countByName(provenance, 'ifds'))),
    command('CorpusAsyncPaths', integer(countByName(provenance, 'async_supplement'))),
    command('CorpusBothPaths', integer(countByName(provenance, 'both'))),
    command('CorpusTopTenApiShare', percent(summary.concentration.top10ApiShare)),
    command('CorpusTopFiftyApiShare', percent(summary.concentration.top50ApiShare)),
    command('CorpusApiGini', decimal(concentration.gini, 3)),
    command('CorpusApiHhi', decimal(concentration.hhi, 4)),
    command('CorpusApiEffectiveProjects', decimal(concentration.effectiveProjects, 1)),
    command('CorpusChainMedian', integer(trace.chainLength.median)),
    command('CorpusChainP95', integer(trace.chainLength.p95)),
    command('CorpusPathMedian', integer(trace.taintPathLength.median)),
    command('CorpusPathP95', integer(trace.taintPathLength.p95)),
    command('CorpusPathMaximum', integer(trace.taintPathLength.max)),
    command('CorpusIfdsEdgesMedian', integer(distributions.ifdsEdgesPerProject.median)),
    command('CorpusIfdsEdgesP95', integer(distributions.ifdsEdgesPerProject.p95)),
    command('CorpusIfdsEdgesMaximum', integer(distributions.ifdsEdgesPerProject.max)),
    command('CorpusRuntimeMedian', decimal(distributions.runtimeMs.median / 1000, 1)),
    command('CorpusRuntimeP95', decimal(distributions.runtimeMs.p95 / 1000, 1)),
    command('CorpusRuntimeMaximum', decimal(distributions.runtimeMs.max / 1000, 1)),
    command('CorpusMethodsRuntimeRho', decimal(
      correlations.methodsVsRuntimeMs.spearmanRho,
      3,
    )),
    command('CorpusMethodsApisRho', decimal(
      correlations.methodsVsApis.spearmanRho,
      3,
    )),
    command('CorpusCloneMaxShift', decimal(maxCloneShift(redundancy), 3)),
    command('CorpusSourceFiles', integer(redundancy.corpusStructure.sourceFiles)),
    command('CorpusUniqueFingerprints', integer(
      redundancy.corpusStructure.uniqueSourceFingerprints,
    )),
    command('CorpusExactCloneClusters', integer(
      redundancy.corpusStructure.exactDuplicateClusters,
    )),
    command('CorpusNearCloneClusters', integer(
      redundancy.corpusStructure.nearDuplicateClusters,
    )),
  ];

  const categoryNames = [
    ['HardwareIdentity', 'device_identity.hardware'],
    ['NetworkConnectivity', 'network.connectivity'],
    ['ScreenIdentity', 'device_identity.screen'],
    ['AccountData', 'user_data.account'],
    ['ClipboardData', 'user_data.clipboard'],
  ];
  for (const [macro, name] of categoryNames) {
    const count = byName(categories, name).count;
    lines.push(command(`Corpus${macro}Count`, integer(count)));
    lines.push(command(`Corpus${macro}Share`, percent(
      count / totals.privacyApiUsages,
    )));
  }
  const sinkNames = [
    ['Log', 'log'],
    ['Ui', 'ui_display'],
    ['Storage', 'storage'],
    ['Return', 'data_return'],
    ['Network', 'network'],
  ];
  for (const [macro, name] of sinkNames) {
    const count = byName(sinks, name).count;
    lines.push(command(`Corpus${macro}SinkCount`, integer(count)));
    lines.push(command(`Corpus${macro}SinkShare`, percent(count / totals.sinks)));
  }

  fs.mkdirSync(path.dirname(path.resolve(args.output)), { recursive: true });
  fs.writeFileSync(path.resolve(args.output), `${lines.join('\n')}\n`);
  console.log(`Wrote ${args.output}`);
}

if (require.main === module) main();
